In [2]:
%load_ext autoreload
import sys
from pathlib import Path

sys.path.append(str(Path('..').resolve()))

In [3]:
%autoreload 2
from models import QuartoCNN
import torch
model = QuartoCNN()
# torch.manual_seed(42)
input_board = torch.randn(2, 16, 4, 4)
input_piece = torch.rand(2, 16)
input_piece = torch.round(input_piece)
input_board = abs(torch.round(input_board/torch.max(input_board)))
print(input_board)
out1, out2 = model.predict(input_board, input_piece, TEMPERATURE=0.1, DETERMINISTIC=False)
print(out1[:,:5])
print(out2[:,:5])

[06-03 20:35:06][INFO] 2025-06-03 20:35:06.123575
tensor([[[[0., 0., 0., 1.],
          [0., 1., 0., 0.],
          [1., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [1., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 1.],
          [0., 1., 0., 1.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 1.],
          [1., 0., 0., 0.],
          [0., 1., 0., 0.],
          [0., 0., 0., 0.]],

         [[1., 1., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 1., 0.],
          [0., 0., 0., 0.]],

         [[0., 1., 0., 0.],
          [0., 0., 0., 1.],
          [0., 0., 1., 0.],
          [1., 0., 0., 0.]],

         [[1., 1., 0., 0.],
          [1., 1., 1., 0.],
          [0., 0., 0., 0.],
          [0., 0., 1., 0.]],

         [[0., 1., 0., 1.],
          [0., 0., 0., 1.],
          [0., 1., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 1.],
          

In [4]:
model.export_model("aqui3")

'C:\\Users\\Jonathan Zea\\Documents\\GitHub\\hierarchical-SAE\\models/weights/QuartoCNN1\\20250603_2035-aqui3.pt'

In [5]:
model_load = QuartoCNN.from_file(
    "C:\\Users\\Jonathan Zea\\Documents\\GitHub\\hierarchical-SAE\\models/weights/QuartoCNN1\\20250601_1227-aqui3.pt"
)

In [10]:
a, b = model_load.forward(input_board, input_piece)

In [15]:
b

tensor([[ 0.0876,  0.0185, -0.0526,  0.0531,  0.1042,  0.0057, -0.0370, -0.0508,
         -0.0775, -0.0640, -0.0071,  0.0690,  0.0491, -0.0749,  0.0130, -0.0066],
        [ 0.0812,  0.0275, -0.0405,  0.0567,  0.1186, -0.0019, -0.0421, -0.0494,
         -0.0795, -0.0710, -0.0160,  0.0802,  0.0330, -0.0669,  0.0042,  0.0016]],
       grad_fn=<TanhBackward0>)

In [6]:
out1, out2 = model_load.predict(
    input_board, input_piece, TEMPERATURE=0.1, DETERMINISTIC=False
)
print(out1[:, :5])
print(out2[:, :5])

tensor([[14,  0, 15, 13, 12],
        [ 6, 10, 15, 14,  2]])
tensor([[13,  8,  5,  4, 10],
        [10,  0, 12, 14, 15]])
