In [5]:
%load_ext autoreload
import sys
from pathlib import Path

sys.path.append(str(Path('..').resolve()))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
%autoreload 2
from models import QuartoCNN
import torch
model = QuartoCNN()
# torch.manual_seed(42)
input_board = torch.randn(2, 16, 4, 4)
input_piece = torch.rand(2, 16)
input_piece = torch.round(input_piece)
input_board = abs(torch.round(input_board/torch.max(input_board)))
print(input_board)
out1, out2 = model.predict(input_board, input_piece, TEMPERATURE=0.1, DETERMINISTIC=False)
print(out1[:,:5])
print(out2[:,:5])

[06-01 12:27:45][INFO] 2025-06-01 12:27:45.210886
tensor([[[[0., 0., 0., 0.],
          [0., 1., 1., 0.],
          [0., 0., 1., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 1.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 1.]],

         [[0., 0., 0., 0.],
          [0., 1., 0., 1.],
          [1., 1., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 1., 0., 0.],
          [1., 0., 0., 1.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 1., 0., 1.],
          [1., 0., 0., 1.]],

         [[0., 0., 0., 0.],
          [0., 0., 1., 0.],
          [0., 0., 1., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [1., 0., 0., 0.],
          [1., 0., 0., 1.],
          [0., 0., 1., 1.]],

         [[0., 1., 0., 0.],
          [1., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 1., 0.],
          

In [7]:
model.export_model("aqui3")

'C:\\Users\\Jonathan Zea\\Documents\\GitHub\\hierarchical-SAE\\models/weights/QuartoCNN1\\20250601_1227-aqui3.pt'

In [16]:
model_load = QuartoCNN.from_file(
    "C:\\Users\\Jonathan Zea\\Documents\\GitHub\\hierarchical-SAE\\models/weights/QuartoCNN1\\20250601_1227-aqui3.pt"
)

In [21]:
out1, out2 = model_load.predict(
    input_board, input_piece, TEMPERATURE=0.1, DETERMINISTIC=False
)
print(out1[:, :5])
print(out2[:, :5])

tensor([[12, 11, 15,  8,  9],
        [12, 14,  9,  3,  1]])
tensor([[ 5, 12,  8,  1, 14],
        [ 0,  4, 14, 15, 13]])
